security:
    # Active le nouveau système de sécurité Symfony
    enable_authenticator_manager: true

    # Gestion du hash des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            # Utilise la base de données (Entity User)
            entity:
                class: App\Entity\User

                # Connexion avec le champ "name" (ex: ina)
                property: name

    firewalls:
        dev:
            # Désactive la sécurité pour les assets (css, js, images, profiler)
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Gestion du formulaire de connexion
            form_login:
                login_path: admin_login
                check_path: admin_login

            # (Optionnel mais recommandé)
            # Permet de se déconnecter proprement
            logout:
                path: app_logout
                target: /

    role_hierarchy:
        # Un admin est aussi un user
        ROLE_ADMIN: ROLE_USER

    access_control:
        # 🔒 Sécurisation des pages admin
        # Seuls les admins peuvent accéder à /admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Le reste du site est accessible librement

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10